# Advanced Numpy 

## Random Number Generation and Setting Seeds
### Random Number Generation
- np.random

In [ ]:
import numpy as np

#this will create the random array of 3x3 matrix, with uniform distribution from 0 to 1
random_array = np.random.rand(3,3)
print(random_array)

[[0.90122101 0.5651107  0.50649932]
 [0.78852412 0.79309594 0.32071366]
 [0.06567386 0.30638599 0.98504548]]


---

### Generating random integer
`np.random.randint(0,10, size=(2,3))`
will generate the matrix of 2x3
where integer ranging from 0 to 10

In [ ]:

random_integer = np.random.randint(0,10, size=(2,3))
print(random_integer)

[[4 2 6]
 [1 7 2]]


Setting the Seed: You call np.random.seed(some_integer_value), where some_integer_value can be any integer, like 42. This initializes the random number generator with a specific state.

In [8]:
np.random.seed(42)
random_integer = np.random.randint(0,10, size=(2,3))
print(random_integer)


[[6 3 7]
 [4 6 9]]


---

### Question
- Generate the random dataset
- Replace the values which are greater then 25 to 0
- Calculate it stats like sum, mean, standard deviation

In [13]:
#Generate Random Dataset
dataset = np.random.randint(1,51, size=(5,5))
print("Original Matrix",dataset, sep = "\n")
# Filter values > 25 and replace with 0
dataset[dataset>25] = 0;
print("Modified Dataset: \n", dataset)

#calculate summary stats
print("Sum:", np.sum(dataset))
print("Mean",np.mean(dataset))
print("Standard Deviation:", np.std(dataset))


Original Matrix
[[17  8 35 35 33]
 [ 5 42 39 41 28]
 [ 7  9  8 12 34]
 [33 48 23 24 37]
 [35 44 40 22 27]]
Modified Dataset: 
 [[17  8  0  0  0]
 [ 5  0  0  0  0]
 [ 7  9  8 12  0]
 [ 0  0 23 24  0]
 [ 0  0  0 22  0]]
Sum: 135
Mean 5.4
Standard Deviation: 7.939773296511683
