## Numpy

In [1]:
import numpy as np

### Creating Numpy Arrays

In [ ]:
#Creaying Normal Numpy Array
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
#Array with zeroes
zeroes = np.zeros((3,3))
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# To combine two numpy
# Create two sample single-column arrays
array1 = np.array([[10], [20], [30]])
array2 = np.array([['A'], ['B'], ['C']])

# Combine them horizontally using np.hstack()
combined_array = np.hstack((array1, array2))

# Print the result
print(combined_array)